core:
  mode: "debug" #gin mode support debug, test, release
  version: "yq-starter-1.0"
  address: "" # ip address to bind (default: any)
  port: "8080" # ignore this port number if auto_tls is enabled (listen 443).  
log:
  gin_log: "/tmp/yq-starter/logs/gin.log" # define log path like "logs/gin.log"
  format: "json" # string or json
  access_log: "/tmp/yq-starter/logs/access.log" # stdout: output to console, or define log path like "logs/access.log"
  access_level: "debug"
  error_log: "/tmp/yq-starter/logs/error.log" # stderr: output to console, or define log path like "logs/error.log"
  error_level: "error"
database:
  engine: "sqlite3" # support mysql, sqlite3
  log_mode: true # 是否打印sql语句
  mysql: 
    url: "user:password@/dbname?charset=utf8&parseTime=True&loc=Local"
  sqlite3: 
    url: "/tmp/yq-starter/app_test.db"